<?php

namespace App\Http\Requests\Product;

use App\Foundations\RequestAuthTrait;
use Illuminate\Foundation\Http\FormRequest;

class CreateProduct extends FormRequest
{
    use RequestAuthTrait;

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
        ];
    }

    public function get($key, $default = null)
    {
        if ($key === 'prod_price') {
            // 过滤价格精确到分
            return intval(floatval(parent::get($key, $default)) * 100);
        }
        return parent::get($key, $default); // TODO: Change the autogenerated stub
    }

    public function getBody()
    {
        $data = $this->only([
            'prod_cover_id',
            'prod_type_id',
            'prod_title',
            'prod_body',
            'prod_desc',
            'prod_price',
        ]);

        if ($data['prod_price']) {
            $data['prod_price'] = intval(floatval($data['prod_price']) * 100);
        }
        return $data;
    }
}
